@hostname=localhost
@port=4000

GET http://{{hostname}}:{{port}}/v1/transactions

###

GET http://{{hostname}}:{{port}}/panic

###

GET http://{{hostname}}:{{port}}/ping

###

GET http://{{hostname}}:{{port}}/v1/transactions/3

###

GET http://{{hostname}}:{{port}}/v1/transactions?concept=supermercado

###

GET http://{{hostname}}:{{port}}/v1/transactions?value=5000

###

GET http://{{hostname}}:{{port}}/v1/transactions?description=semana

###

GET http://{{hostname}}:{{port}}/v1/transactions?sort=concept

###

GET http://{{hostname}}:{{port}}/v1/transactions?page=1&page_size=3

###

GET http://{{hostname}}:{{port}}/v1/transactions?concept=supermercado&value=5000

###

GET http://{{hostname}}:{{port}}/v1/transactions?page=0&page_size=0&sort=hello

###

GET http://{{hostname}}:{{port}}/v1/users

###

POST http://{{hostname}}:{{port}}/v1/users
Content-Type: application/json
Accept: application/json

{
  "first_name": "Oliver",
  "last_name": "Hernandez",
  "email": "oliverjhernandez@gmail.com",
  "passwd": "oliver123"
}
