GET http://localhost:4000/v1/transactions

### 

GET http://localhost:4000/panic

### 

GET http://localhost:4000/v1/transactions/3

###

GET http://localhost:4000/v1/transactions?concept=supermercado

###

GET http://localhost:4000/v1/transactions?value=5000

###

GET http://localhost:4000/v1/transactions?description=semana

###

GET http://localhost:4000/v1/transactions?sort=concept

###

GET http://localhost:4000/v1/transactions?page=1&page_size=3

###

GET http://localhost:4000/v1/transactions?concept=supermercado&value=5000

###

GET http://localhost:4000/v1/transactions?page=0&page_size=0&sort=hello

###

GET http://localhost:4000/v1/users
