@BASE_URL = http://localhost:4000/v1


# @env-stdin-cmd JWT_CONTEXT jq -r '.authentication_token.token'
POST {{BASE_URL}}/tokens/authentication HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "alice@example.com",
  "password": "pa55word"
}

###

POST {{BASE_URL}}/accounts HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_CONTEXT}}

{
  "title": "silly_account",
  "user_id": 1,
  "entity_id": 5
}

###

GET {{BASE_URL}}/accounts?sort=-entity_id
Accept: application/json
Authorization: Bearer {{JWT_CONTEXT}}

### 

GET {{BASE_URL}}/accounts/14 HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_CONTEXT}}

###

PATCH {{BASE_URL}}/accounts/14
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_CONTEXT}}

{
  "title": "Corina",
  "currency": 3
}

###

DELETE {{BASE_URL}}/accounts/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_CONTEXT}}
